@startuml
skinparam monochrome true

Implementation <<Application>>

(Start Evolution) as (Evolve)
(Objective & Fitness Assignment) as (Evaluation)
'(Evolve with Termination) as (StartWithTermination)

'(StartWithTermination) <. (Termination) : <<include>>
'(StartWithTermination) <. (Evolve) : <<include>>

(Evolve) <. (Terminate) : <<extend>>

'Implementation --> (StartWithTermination)
Implementation --> (Evolve)
'Implementation ---> (Terminate)
Implementation -> (Access Result)

(Evolve) <.. (Population Initialization) : <<include>>
(Evolve) <.. (Reproduction) : <<include>>
(Evolve) <... (Offspring Selection) : <<include>>

(Population Initialization)  <.. (Evaluation) : <<include>>
(Reproduction)  <. (Evaluation) : <<include>>

@enduml