// <auto-generated />
using System;
using Albar.AssistantAssignment.WebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Albar.AssistantAssignment.WebApp.Migrations
{
    [DbContext(typeof(AssignmentDatabase))]
    [Migration("20190714095812_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Assistant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("GroupId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.AssistantSubject", b =>
                {
                    b.Property<int>("AssistantId");

                    b.Property<int>("SubjectId");

                    b.Property<string>("Assessments");

                    b.HasKey("AssistantId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssistantSubject");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Day");

                    b.Property<int?>("GroupId");

                    b.Property<int>("Lab");

                    b.Property<int>("Session");

                    b.Property<int?>("SubjectId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssessmentsThreshold");

                    b.Property<int>("AssistantPerScheduleCount");

                    b.Property<int?>("GroupId");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Assistant", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany("Assistants")
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.AssistantSubject", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Assistant", "Assistant")
                        .WithMany("AssistantSubjects")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Subject", "Subject")
                        .WithMany("AssistantSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Schedule", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany("Schedules")
                        .HasForeignKey("GroupId");

                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Subject", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany("Subjects")
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
