// <auto-generated />
using System;
using Albar.AssistantAssignment.WebApp;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Albar.AssistantAssignment.WebApp.Migrations
{
    [DbContext(typeof(AssignmentDatabase))]
    [Migration("20191103112307_UpdateEFCore")]
    partial class UpdateEFCore
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Assistant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Npm")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Assistants");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.AssistantSubject", b =>
                {
                    b.Property<int>("AssistantId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Assessments")
                        .HasColumnType("TEXT");

                    b.HasKey("AssistantId", "SubjectId");

                    b.HasIndex("SubjectId");

                    b.ToTable("AssistantSubject");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Day")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Lab")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Session")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("SubjectId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("SubjectId");

                    b.ToTable("Schedules");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Subject", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AssessmentsThreshold")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssistantPerScheduleCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("Subjects");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Assistant", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.AssistantSubject", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Assistant", "Assistant")
                        .WithMany("AssistantSubjects")
                        .HasForeignKey("AssistantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Subject", "Subject")
                        .WithMany("AssistantSubjects")
                        .HasForeignKey("SubjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Schedule", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Subject", "Subject")
                        .WithMany("Schedules")
                        .HasForeignKey("SubjectId");
                });

            modelBuilder.Entity("Albar.AssistantAssignment.WebApp.Models.Subject", b =>
                {
                    b.HasOne("Albar.AssistantAssignment.WebApp.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");
                });
#pragma warning restore 612, 618
        }
    }
}
